### ISSUE TITLE
Build the (GameActionException) Class

### ISSUE THREAD

**Issue by Omar-Nour** [AliAbdalwahaab/CS4-Marvel-Game-Project#17]
Name : GameActionException
Package : exceptions
Type : Class
Description : Class representing a generic exception that can occur during the game play. These
exceptions arise from any invalid action that is performed. This class has four subclasses; NotEnoughResourcesException, AbilityUseException, LeaderAbilityAlreadyUsedExcecption, and UnallowedMovementException.

**Comment by shamekhjr** [comment]
Add setters and getters (just in case).
