### ISSUE TITLE
Build the (AbilityUseException) Class

### ISSUE THREAD

**Issue by Omar-Nour** [AliAbdalwahaab/CS4-Marvel-Game-Project#19]
Name : AbilityUseException
Package : exceptions
Type : Class
Description : A subclass of GameActionException representing an exception that occurs upon trying
to cast an invalid ability.

**Comment by shamekhjr** [comment]
I think for this one you just need a getter. Unless we would be required to customize the error message to include the ability that the user tried to use even though he doesn't have access to.
