### ISSUE TITLE
 Build the (LeaderAbilityAlreadyUsedExcecption) Class

### ISSUE THREAD

**Issue by Omar-Nour** [AliAbdalwahaab/CS4-Marvel-Game-Project#20]
Name : LeaderAbilityAlreadyUsedExcecption
Package : exceptions
Type : Class
Description : A subclass of GameActionException representing an exception that occurs upon trying
to reuse a leader ability, which is only allowed once.

**Comment by shamekhjr** [comment]
I think for this one you just need a getter. Unless we would be required to customize the error message to include the name of the ability that the user tried for a second time.
