### ISSUE TITLE
Build the (UnallowedMovementException) Class

### ISSUE THREAD

**Issue by Omar-Nour** [AliAbdalwahaab/CS4-Marvel-Game-Project#21]
Name : UnallowedMovementException
Package : exceptions
Type : Class
Description : A subclass of GameActionException representing an exception that occurs upon trying
to preform an unallowed movement.

**Comment by AliAbdalwahaab** [comment]
Built class, awaiting revision. (ALI)

**Comment by shamekhjr** [comment]
Add setters and getters for the exception message (just in case) like with the other exception classes.
