### ISSUE TITLE
Use the Junit test when it arrives on CMS

### ISSUE THREAD

**Issue by AliAbdalwahaab** [AliAbdalwahaab/CS4-Marvel-Game-Project#22]
Wait for tests to arrive in order to test the project's milestone 1.

**Comment by Omar-Nour** [comment]
Junit Tests Arrived, **don't test** until we patch classes according to the new pdf

**Comment by shamekhjr** [comment]
> Junit Tests Arrived, **don't test** until we patch classes according to the new pdf

Don't worry, I will patch my classes and inform you of that in my commits.

**Comment by Omar-Nour** [comment]
Done (406/406 Public Tests Passed)
