### ISSUE TITLE
Missing data from game milestone documentation PDF.

### ISSUE THREAD

**Issue by AliAbdalwahaab** [AliAbdalwahaab/CS4-Marvel-Game-Project#23]
The duration of effects in the different effects classes (e.g. Stun, Shield, SpeedUp etc.) isn't mentioned. We should either consult the TA's or put dummy duration values in order to keep the errors suppressed.

**Comment by Omar-Nour** [comment]
**No errors are present** to be _suppressed_, `duration` values will be passed later on through the `constructors` of these classes during `Instance` creation.
