### ISSUE TITLE
What to do With turnOrder in Game Class?

### ISSUE THREAD

**Issue by Omar-Nour** [AliAbdalwahaab/CS4-Marvel-Game-Project#26]
should we load all  champs or only the chosen 6 (3 for each player) ?

**Comment by shamekhjr** [comment]
According to the updated milestone 1 document, tha availableChampions ArrayList should load all of the available champions to choose from. As for  turnOrder, it says it "contains all characters available to pick from." So I guess that means it should include all of the champions in the game.

**Comment by Omar-Nour** [comment]
Done (initialize with size 6)
