### ISSUE TITLE
Add abilities in Champion constructor (Proposal)

### ISSUE THREAD

**Issue by Omar-Nour** [AliAbdalwahaab/CS4-Marvel-Game-Project#27]
When loading the CSV files, I found that it supplied the abilities for each champ. This means that we should insert the abilities
of champs through their constructor.

**Comment by shamekhjr** [comment]
Well, the constructor (according to the milestone 1 doc at least), doesn't take the abilities arraylist as inputs, nor is there a setter for it since the attribute is read only. I find this confusing😅

**Comment by Omar-Nour** [comment]
we can make an extra constructor with abilities

**Comment by Omar-Nour** [comment]
Done by Shamekh.
