### ISSUE TITLE
Modify Effect class (A bit long)

### ISSUE THREAD

**Issue by shamekhjr** [AliAbdalwahaab/CS4-Marvel-Game-Project#34]
(Note from Shamekh: Maybe we should split this on two people as well)

No objects of type Effect can be instantiated. This class should implement the Cloneable interface
(predefined in Java). Implementing this interface will help us create an exact copy of any subclass of
Effect without needing to call the constructor of its corresponding class. When overriding the needed
method from the Cloneable interface, you should override it as a public method.
This class should also include the following additional methods:-

• void apply(Champion c): This method applies the logic of the effect on the given champion
(Based on what is illustrated in the below table).
• void remove(Champion c): This method should undo the logic that the apply method previously
did on the given Champion. This method is called once the duration of the effect is over.

(Check table given in the Milestone 2 document)

**Comment by Omar-Nour** [comment]
make sure that all effect subclasses correctly add the effects or not add them to the AppliedEffects arrayList
